# SPDX-License-Identifier: GPL-2.0+
#
# Nexell S5P6818 x6818 board (AArch32)

obj-y	:= board.o
obj-y	+= x6818_cmd.o
obj-$(CONFIG_VIDEO_NX) += builtin_logo.o logo_data.o
obj-$(CONFIG_VIDEO_NX_MIPI) += display.o
